---
output: html_document
bibliography: references.bib
---

### Description and sources for simulation parameters

#### Model structure

We use a dynamic epidemiological model, based on the classic SEIR model, to describe the spread and clinical progression of COVID-19, see details in section of *Model*.

#### Model parameters

The behavior of the dynamic SEIR model is determined by a set of rate parameters, including the transmission rates $\beta_*$, the progression rates $\alpha_*$ and $p_*$, the recovery rates $\gamma_*$, and the death rate $q_*$, the subscript $*$ denotes one of the patient groups, mild ($m$), severe ($s$), and critically ill ($c$). While these rates themselves are not generally measured directly in studies, then we applied a Bayesian method with Markov chain Monte Carlo (MCMC) to estimate the parameters of dynamic models for the COVID-19 epidemiological data in both New York State and Hubei Province. To implement the MCMC sampling scheme, we follow the method proposed by @raftery1992. After an initial number of 10,000 burn-iterations, every tenth MCMC sample is retained from the next 200,000 samples. Thus, we obtain 20,000 samples of targeted posterior distributions of the unknown parameters. The stability of the posterior distributions of the unknown parameters was checked by examining the graphics of the runs. The technical details of parameter estimation methods can be found in our paper. All analyses of estimating parameters were done with R software (version 3.6.3; R Foundation for Statistical Computing, Vienna, Austria), with Bayesian Marko-Chain Monte Carlo via the package rjags (version 4-10).

The default parameters for the simulation come from our analysis of the New York State epidemic. The epidemiological data of COVID-19 in New York State, US were mainly obtained from Centers for Disease Control and Prevention of United States, and Johns Hopkins Coronavirus Resource Center (https://coronavirus.jhu.edu/). We collected the cumulative number of infected cases, the current number of confirmed cases, the current number of hospitalized cases, the number of cumulative deaths and the number of cumulative cases from March 16 to June 6, 2020. The data from March 16 to May 31 was used for model building and parameter estimation.

Table 1 Summary of model parameters estimated by MCMC in New York State, US. Users can choose their own values based on other studies or particular regional contexts. 

Parameter                     Value                   Definition       
------------                  ----------------------- --------------------------------------------------
$\beta_m$                     0.0579                        Transmission rate at which infectious individuals in $I_m$ contact susceptibles $S$ and infect them
$\beta_E$                     0.3495                        Transmission rate at which exposed individuals $E$ contact susceptibles $S$ and infect them
$\gamma_m$                    0.0694                        Rate at which infectious individuals in class $I_m$ recover from the disease    
$\gamma_s$                    0.0488                        Rate at which infectious individuals in class $I_s$ recover from the disease   
$\gamma_c$                    0.1297                        Rate at which infectious individuals in class $I_c$ recover from the disease    
$p_s$                         0.0002                        Rate at which infectious individuals in class $I_m$ progress to $I_{s}$
$p_c$                         0.1009                        Rate at which infected individuals in class $I_s$ progress to $I_{c}$
$\alpha_m$                    0.1167                        Rate of progression from the exposed $E$ to infectious class $I_m$
$\alpha_s$                    0.0337                        Rate of progression from the exposed $E$ to infectious class $I_s$
$q_s$                         0.0039                        Death rate for infectious individuals in class $I_{s}$
$q_c$                         0.1745                        Death rate for infectious individuals in class $I_{c}$
$\delta$                      1.35E-08                      Rate at which individuals have been cured but become susceptible again

Table 2 summary of all parameters for COVID-19 clinical progression and disease severity estimated by MCMC in New York State, US.

Quantity                                              Value            Definition       
------------------------------------------            ---------        --------------------------------------------------
Incubation Period                                     6.65 days         Time from exposed to symptoms in mild or severe infections
Duration of mild stage                                14.47 days        Time from symptoms to hospitalization or recovery
Duration of severe stage                              6.53 days         Time from hospitalization to recovery, ICU admission or death
Duration of hospitalized stage                        9.80 days         Time from hospital admission to death
Progression proportion to severe stage                22.61%            Proportion of progressing to severe stage in mild patients
Progression proportion to critical stage              14.85%            Proportion of progressing to critical stage in mild patients
Progression proportion to death                       8.89%             Proportion of progressing to death in mild patients


#### Hospital capacity parameters

One of the biggest dangers of a widespread COVID-19 epidemic is the strain it could place on hospital resources, since individuals with severe and critical infection require hospital care. The critical stage of infection requires mechanical ventilation, which is ICU-level care. Severe infection can be treated in a regular hospital ward. Individuals with mild infection do not require hospitalization, and could recover at home on their own. However, in many countries these individuals have also been hospitalized, likely as a way to isolate them and reduce transmission, as well as to monitor them for progression to more aggressive disease stages. 

The default hospital capacity parameters are estimated for the US, and are expressed as resources per capita. The available hospital beds (in regular wards or on ICU floors) depends on the total number of beds that exist as well as the occupancy level. During flu season (winter months), occupancy levels are generally higher. We report the number of *available* (e.g. unoccupied) beds of both types (Table 3). 
Studies in the pandemic preparedness literature have examined how the capacity to delivery mechanical ventilation during a respiratory pathogen outbreak could be expanded beyond the traditional ICU-bed capacity (aka *conventional capacity*) by using stockpiled ventilators, non-specialist hospital staff, and retro-fitting other hospital rooms [@ajao_assessing_2015]. These expanded delivery levels are called *contingency* and *crisis* capacity. 


Quantity                                        Total      Per 1000 ppl    Source
---------------------------------------------   ---------  -------------   -----------------------
Hospital beds                                   900,000     2.8            [@nchs_table_2017]
Occupancy                                       66%                        [@nchs_table_2017]
ICU beds                                        80,000      0.26           [@sccm_2010]
Occupancy                                       68%                        [@sccm_2010]
$\uparrow$ flu season occupany                  7%                         [@ajao_assessing_2015]
Available hospital beds                         264,000     0.82           From above     
Available ICU beds                              22,000      0.071          From above  
Conventional Mechanical Ventilation Capacity    20,000      0.062          [@ajao_assessing_2015]
Contingency Mechanical Ventilation Capacity     50,000      0.15           [@ajao_assessing_2015]
Critical Mechanical Ventilation Capacity        135,000     0.24           [@ajao_assessing_2015]


Table 2. US hospital capacity. Values are for adults beds only. 

#### References



