---
title: "DSEIR"
output: html_notebook
---

### Model

In the classical SEIR model, the human-to-human transmission of COVID-19 is modeled using a compartmental representation of the disease where an individual occupies one of the four states: Susceptible ($S$), Exposed ($E$), Infectious ($I$) and Removed ($R$). Susceptible individuals $S$ can acquire the virus through contacts with individuals in the infectious compartment, and become exposed. The exposed individuals $E$ are infected but not yet infectious. They experience an incubation duration and progress to the infectious stage with certain rate. The infectious individuals can progress into the removed stage (usually recovered with immunity) with another rate. 

To characterize the hospital utilization for patients with COVID-19, we generalize the classical SEIR model by introducing a few new states according to the actual situation of patients in hospital. Here the infectious stage includes all individuals who are confirmed COVID-19 cases $I$, which is composed of three sub-compartments ($I_m$, $I_s$, $I_c$) based on different clinical stages, and the clinical descriptions of the different stages of infection $I$ are given below. 

* **Clinical stages**

  * Mild stage ($I_m$): These individuals include patients who have symptoms like fever and cough and may have mild pneumonia. Hospitalization is not required in United States, but such individuals are required to admit to temporary hospitals in China.
  * Severe stage ($I_s$): These individuals was characterized by dyspnea, respiratory frequency ≥ 30/minute, blood oxygen saturation ≤93%, PaO2/FiO2 ratio <300, and/or lung infiltrates >50% within 24–48 hours. Hospitalization and supplemental oxygen were generally required.
  * Critical stage ($I_c$): These individuals were those that exhibited respiratory failure, septic shock, and/or multiple organ dysfunction/failure. Treatment in an ICU, often with mechanical ventilation, was typically required.

The removed stage $R$ includes two sub-compartments: the dead compartment ($D$) and the recovered compartment ($R$). Then we use a dynamic epidemiological model, containing the new stages described above, to describe the spread and clinical progression of COVID-19. All variables involved in the dynamic SEIR (DSEIR) model we proposed are described as follows. 

* **Variables**

  * $S$: Susceptible individuals.
  * $E$: Exposed individuals - infected but not yet infectious or symptomatic.
  * $I_m$: Infectious individuals with mild symptoms.
  * $I_s$: Infectious individuals with severe symptoms.
  * $I_c$: Infectious individuals with critical symptoms. 
  * $R$: Individuals who have recovered from disease but are not completely immune.
  * $D$: Dead individuals.
  * $N$: Total population size, where $N=S+E+I_m+I_s+I_c+R+D$.

In this DSEIR model, we supposed that exposed individuals $E$ have not been confirmed, therefore, they are not only infected but also infectious. We assumed that an individual being susceptible $S$ or at risk can only be infected by exposed individuals $E$ or mild patients $I_m$, since severe $I_s$ or critically ill patients $I_c$ were hospitalized and had a very small (ignorable) probability to infect others. Then assume that individuals at stage $I_m$ and $E$ may transmit the infection with the transmission rate $\beta_m$ and $\beta_E$. For one individual in this epidemiological system, the rate of progressing from the exposed stage $E$ to the infectious stage is $\alpha_m+\alpha_s$, where $\frac{\alpha_m}{\alpha_m+\alpha_s}$ is the probability of conversion from exposed state to the stage of mild illness, $\frac{\alpha_s}{\alpha_m+\alpha_s}$ is the probability of direct disease to severe stage. In addition, most infectious individuals begin with *mild* infection ($I_m$), from which they either recover at rate $\gamma_m$, or progress to *severe* stage ($I_s$) at rate $p_s$. Severe patients are either cured at rate ($\gamma_s$), enter the next stage ($I_c$) at rate $p_c$, or die at rate $q_s$. Individuals with critical infection recover at rate $\gamma_c$ or die at rate $q_c$. Recovered individuals are tracked by class $R$ and are assumed to return to the infected system at the rate $\delta$, which means that patients who have been cured are not completely immune. We sort out all the parameters that appear in the model and show them as follows.

* **Parameters**

  * $\beta_m$: Transmission rate at which infectious individuals in $I_m$ contact susceptibles $S$ and infect them.
  * $\beta_E$: Transmission rate at which exposed individuals $E$ contact susceptibles $S$ and infect them.
  * $\alpha_m$: Rate of progression from the exposed $E$ to infectious class $I_m$.
  * $\alpha_s$: Rate of progression from the exposed $E$ to infectious class $I_s$.
  * $\gamma_m$: Rate at which infectious individuals in class $I_m$ recover from the disease.
  * $\gamma_s$: Rate at which infectious individuals in class $I_s$ recover from the disease.
  * $\gamma_c$: Rate at which infectious individuals in class $I_c$ recover from the disease.
  * $p_s$: Rate at which infectious individuals in class $I_m$ progress to $I_{s}$.
  * $p_c$: Rate at which infected individuals in class $I_s$ progress to $I_{c}$.
  * $q_s$: Death rate for infectious individuals in class $I_{s}$.
  * $q_c$: Death rate for infectious individuals in class $I_{c}$.
  * $\delta$: Rate at which individuals have been cured but become susceptible again.
 
### Equations

Mathematically, our model is expressed as a system of ordinary differential equations:

\begin{equation}
\frac{dS}{dt}=-\frac{ \left( \beta_m I_m +\beta_E E  \right) S}{N}+\delta R \\
\end{equation}

\begin{equation}
\frac{dE}{dt}=\frac{ \left( \beta_m I_m +\beta_E E \right) S}{N}- \left( \alpha_m+\alpha_s \right) E \\
\end{equation}

\begin{equation}
\frac{dI_m}{dt}= \alpha_m E -\left ( \gamma_m+p_s \right ) I_m \\
\end{equation}

\begin{equation}
\frac{dI_s}{dt}=  \alpha_s E+ p_s I_m -\left ( \gamma_s+p_c+q_s \right ) I_s \\
\end{equation}

\begin{equation}
\frac{dI_c}{dt}= p_c I_s -\left ( \gamma_c+ q_c \right ) I_c \\
\end{equation}

\begin{equation}
\frac{dR}{dt}=\gamma_m I_m+\gamma_s I_s+\gamma_c I_c -\delta R \\
\end{equation}

\begin{equation}
\frac{dD}{dt}=q_s I_s+q_c I_c
\end{equation}

### Key parameters

**Key parameters for COVID-19 clinical progression**

* Incubation period (the time between exposure to an infected source and the development of symptoms): $\frac{1}{\alpha_m+\alpha_s}$
* Time from symptoms to hospital admission: $\frac{1}{\gamma_m+p_s}$
* Time from hospital admission to critical care: $\frac{1}{\gamma_s+p_c+q_s}$
* Time from hospital admission to death: $\frac{1}{\gamma_s+p_c+q_s}+\frac{1}{\gamma_c+q_c}$

**Key parameters for COVID-19 disease severity**

* Proportion of progressing to severe stage in mild patients: 

$\qquad \qquad \qquad \qquad \frac{\alpha_s}{\alpha_m+\alpha_s}+\frac{\alpha_m}{\alpha_m+\alpha_s} \frac{p_s}{\gamma_m+p_s}$

* Proportion of progressing to critical stage in mild patients: 

$\qquad \qquad \qquad \; \left( \frac{\alpha_s}{\alpha_m+\alpha_s}+\frac{\alpha_m}{\alpha_m+\alpha_s} \frac{p_s}{\gamma_m+p_s} \right)\frac{p_c}{\gamma_s+p_c+q_s}$

* Proportion of progressing to death in mild patients: 

$\qquad \quad \left( \frac{\alpha_s}{\alpha_m+\alpha_s}+\frac{\alpha_m}{\alpha_m+\alpha_s} \frac{p_s}{\gamma_m+p_s} \right) \left(\frac{q_s}{\gamma_s+p_c+q_s} +\frac{p_c}{\gamma_s+p_c+q_s} \frac{q_c}{\gamma_c+q_c}  \right)$

**Relating clinical observations to model parameters**

To determine the model parameters consistent with current clinical data, we collect the following values from the slider values chosen by the user, and then use the formulas below to relate them to the rate parameters in the model. Note that the slider inputs for time intervals are averages durations. 

* DurIncub:  Average incubation period, days.
* DurMild: Average duration from symptoms to hospital admission, days.
* DurSevere: Average duration from hospital admission to critical care, days.
* DurICU: Average time from ICU admission to recover or die, days.

Note that

* $\alpha_m+\alpha_s$=1/DurIncub

* $\gamma_m$=1/DurMild-$p_s$

* $\gamma_s$=1/DurSevere-$p_c$-$q_s$

* $\gamma_c$=1/DurICU-$q_c$


### Basic reproductive ratio

Idea: $R_0$ is the sum of: 

1. the average number of secondary infections generated from an individual in stage $E$. 

2. the probability that an exposed individual $E$ progresses to $I_m$ multiplied by the average number of secondary infections generated from an individual in stage $I_m$.

\begin{equation}
R_0  = \frac{\beta_E}{\alpha_s+\alpha_m} + \frac{\alpha_m}{\alpha_s+\alpha_m}  \frac{\beta_m}{p_s+\gamma_m} 
\end{equation}

### Special assumptions

* Certain exposed individuals can directly progress to severe stage.
* Infectious individuals must pass through a severe stage before reaching a critical stage.
* Only patients in severe or critical stage could progress to death stage.

