#---% Generated by riskcalc: feel free to edit or 'Run App' %---
server <-
  
  # Define the server
  function(input, output, session) {
    
    # Make a reactive input data frame
    newdat <-
      eventReactive(
        input$run_calculator, {
          
          tibble(
            # use most frequent value or median for the zero coefficients
            age_at_dx = 64,
            sexMale = ifelse(input$sex == "Male", 1, 0),
            `lateralityRight eye` = 0,
            symptomsYes = 0,
            `presenting_bcva20/20` = 0,
            `dist_to_on_mm>=3mm` = ifelse(input$dist_to_on_mm == ">=3mm", 1, 0),
            `dist_to_fov_mm>=3mm` = 0,
            initial_lbd_mm = 8,
            thickness = input$initial_max_height_mm,
            srf_initial = as.numeric(input$srf_initial),
            op_initial = as.numeric(input$op_initial),
            drusen_initial = as.numeric(input$drusen),
            rpe_atrophy_initial = 0) %>% 
            # then it needs to be a matrix
            as.matrix()
          
        })
    
    # Get predictions
    pred_mel = reactive({
      predict(
        cvfit, 
        newx = newdat(), 
        s = "lambda.min", 
        type = "response")
    })
    
    # Show result
    output$result <-
      renderDataTable(
        {
          
          # Make the data frame containing results
          data.frame(Result = "Predicted probability of melanoma at present", Value = paste0(round(pred_mel()[1, ]*100, 1), "%")) 
          
        },
        options =
          list(
            pageLength = 10,
            lengthMenu = 0,
            searching = 0,
            info = 0,
            paging = 0,
            initComplete =
              DT::JS(
                "function(settings, json) {
                    $(this.api().table().header()).css({'background-color': '#606060', 'color': '#fff'});
                  }"
              )
          ),
        rownames = FALSE
      )
    
  }
