#---% Generated by riskcalc: feel free to edit or 'Run App' %---
ui <-
  
  # Make the page
  fluidPage(
    
    # Set the (default) theme
    theme = shinytheme("flatly"),
    
    # Function for email prompting
    tags$script(
      HTML(
        'function sendEmail() {
        var txt;
        if (confirm("This is a mailbox for reporting website errors to programmers for the risk calculator website.  If you have questions or concerns about a specific calculator, please use the calculator Author Contact Information found on the publication for that calculator.  Each calculator is documented by a specific publication with a corresponding author.")) {
          window.open("mailto:rcalcsupport@ccf.org");
        }
      }'
      )
    ),
    
    # Tag for tracking app usage (on server) via Google Analytics
    tags$head(ga_tag),
    
    # Make the title panel
    titlePanel("Small Choroidal Melanoma Predictor"),
    
    # Make the default layout
    sidebarLayout(
      
      # Create the side bar with input objects
      sidebarPanel(
        radioButtons(
          inputId = "dist_to_on_mm",
          label = "Distance to optic disk (mm)",
          choices = list("<3mm", ">=3mm")
        ),
        radioButtons(
          inputId = "sex",
          label = "Sex",
          choices = list("Male", "Female")
        ),
        sliderInput(
          inputId= "initial_max_height_mm",
          label = "Height (mm)",
          min = 1,
          max = 2.5,
          value = 1.5,
          step = 0.1
        ),
        checkboxInput(
          inputId = "srf_initial",
          label = "Subretinal fluid",
          value = FALSE
        ),
        checkboxInput(
          inputId = "op_initial",
          label = "Orange pigment",
          value = FALSE
        ),
        checkboxInput(
          inputId = "drusen",
          label = "Drusen",
          value = FALSE
        )
      ),
      
      # Create the main display panel
      mainPanel(
        
        # Add button for calculation
        actionButton(inputId = "run_calculator", "Run Calculator"),
        br(),
        hr(),
        
        # Make the table output
        dataTableOutput(outputId = "result"),
        br(),
        
        ## Information panels/links
        
        # Citation
        wellPanel(
          h3("Click Below for Calculator and Author Contact Information"),
          HTML("<p>[1] Zabor, E. C., Raval, V., Luo, S., Pelayes, D. E., & Singh, A. D. (2022).
      <a href = 'https://pubmed.ncbi.nlm.nih.gov/35356604/'> A Prediction Model to Discriminate Small Choroidal Melanoma from Choroidal Nevus</a>
      . Ocular oncology and pathology, 8(1), 71–78. https://doi.org/10.1159/000521541</p>"),
          fluidRow(column(width = 12,
                          HTML("<p><i>This predictor is applicable to patients with small choroidal melanocytic lesions (i.e. at least 1mm and not more than 3.5mm in height and/or at
least 1mm and not more than 15mm in largest basal diameter).</i></p>")
          )
          )
        ),
        
        # Disclaimer
        wellPanel(
          h3("Disclaimer"),
          p("No Medical Advice. ALTHOUGH SOME CONTENT MAY BE PROVIDED BY INDIVIDUALS IN THE MEDICAL PROFESSION, YOU ACKNOWLEDGE THAT PROVISION OF SUCH CONTENT DOES NOT CREATE A MEDICAL PROFESSIONAL-PATIENT RELATIONSHIP AND DOES NOT CONSTITUTE AN OPINION, MEDICAL ADVICE, PROFESSIONAL DIAGNOSIS, SERVICE OR TREATMENT OF ANY CONDITION. Access to general information is provided for educational purposes only, through this site and links to other sites. Content is not recommended or endorsed by any doctor or healthcare provider. The information and Content provided are not substitutes for medical or professional care, and you should not use the information in place of a visit, call, consultation or the advice of your physician or other healthcare provider. You are liable or responsible for any advice, course of treatment, diagnosis or any other information, services or product obtained through this site.")
        ),
        
        # Links
        p(
          a("Homepage", href = "../", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Website Error Messages", href = "javascript:sendEmail()", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (iOS Safari)", href = "https://support.apple.com/guide/iphone/bookmark-favorite-webpages-iph42ab2f3a7/ios#iph4f9a47bbc", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (Android)", href = "https://www.cnet.com/tech/mobile/adding-one-touch-bookmarks-to-your-androids-home-screen/", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Source Code", href = "https://github.com/ClevelandClinicQHS/riskcalc-website/tree/main/SCMprediction", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif;font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          style = "text-align: center;"
        ),
        
        # Logo (to render on server)
        img(src = "../logo-ccf.png", style = "max-width:30%; max-height:100%;")
      )
    )
  )
