#---% Generated by riskcalc: feel free to edit or 'Run App' %---
ui <-
  
  # Make the page
  fluidPage(
    
    # Set the (default) theme
    theme = shinytheme("flatly"),
    
    # Function for email prompting
    tags$script(
      HTML(
        'function sendEmail() {
        var txt;
        if (confirm("This is a mailbox for reporting website errors to programmers for the risk calculator website.  If you have questions or concerns about a specific calculator, please use the calculator Author Contact Information found on the publication for that calculator.  Each calculator is documented by a specific publication with a corresponding author.")) {
          window.open("mailto:rcalcsupport@ccf.org");
        }
      }'
      )
    ),
    
    # Tag for tracking app usage (on server) via Google Analytics
    tags$head(ga_tag),
    
    # Make the title panel
    titlePanel("Iris Melanoma Predictor"),
    
    # Make the default layout
    sidebarLayout(
      
      # Create the side bar with input objects
      sidebarPanel(
        sliderInput(
          inputId= "lbd",
          label = "Largest basal diameter (mm)",
          min = 0.5,
          max = 11.1,
          value = 3,
          step = 0.1
        ),
        sliderInput(
          inputId= "height",
          label = "Height (mm)",
          min = 0.2,
          max = 4.2,
          value = 1,
          step = 0.1
        ),
        radioButtons(
          inputId = "iris_location",
          label = "Iris location",
          choices = 
            list("Peripheral", 
                 "Pupillary", 
                 "Central", 
                 "Pan iris"
            )
        ),
        radioButtons(
          inputId = "quadrant",
          label = "Quadrantic location",
          choices = 
            list("Inferior-temporal", 
                 "Superior-nasal",    
                 "Superior-temporal", 
                 "Inferior-nasal"
            )
        ),
        strong("Other present features"),
        checkboxInput(
          inputId = "pigment_dispersion",
          label = "Pigment dispersion",
          value = FALSE
        ),
        checkboxInput(
          inputId = "feeder_intrinsic",
          label = "Feeder  or intrinsic vessel",
          value = FALSE
        ),
        checkboxInput(
          inputId = "ectropion_corectopia",
          label = "Ectropion uvea or corectopia",
          value = FALSE
        ),
        checkboxInput(
          inputId = "angle_cbd",
          label = "Angle or iris root involvement",
          value = FALSE
        )
      ),
      
      # Create the main display panel
      mainPanel(
        
        # Add button for calculation
        actionButton(inputId = "run_calculator", "Run Calculator"),
        br(),
        hr(),
        
        # Make the table output
        dataTableOutput(outputId = "result"),
        br(),
        
        ## Information panels/links
        
        # Citation
        wellPanel(
          h3("Click Below for Calculator and Author Contact Information"),
          HTML("<p>[1] Singh A, Melendez-Moreno A, Krohn J, Zabor EC.
      <a href = 'https://pubmed.ncbi.nlm.nih.gov/38609162/'> Predictive model for iris melanoma</a>
      . Br J Ophthalmol. 2024 Oct 22;108(11):1598-1604. doi: 10.1136/bjo-2023-324558. PMID: 38609162.</p>"),
          fluidRow(column(width = 12,
                          HTML("<p><i>This predictor is applicable to patients with iris melanocytic tumors.</i></p>")
          )
          ),
          fluidRow(column(width = 12,
                          HTML("<p><i>Note that in the development data, tumor seeding, glaucoma, and hyphema were present only in melanoma patients and therefore could not be included in the prediction model as they represented perfect prediction in these data.</i></p>")
          )
          )
          
        ),
        
        # Disclaimer
        wellPanel(
          h3("Disclaimer"),
          p("No Medical Advice. ALTHOUGH SOME CONTENT MAY BE PROVIDED BY INDIVIDUALS IN THE MEDICAL PROFESSION, YOU ACKNOWLEDGE THAT PROVISION OF SUCH CONTENT DOES NOT CREATE A MEDICAL PROFESSIONAL-PATIENT RELATIONSHIP AND DOES NOT CONSTITUTE AN OPINION, MEDICAL ADVICE, PROFESSIONAL DIAGNOSIS, SERVICE OR TREATMENT OF ANY CONDITION. Access to general information is provided for educational purposes only, through this site and links to other sites. Content is not recommended or endorsed by any doctor or healthcare provider. The information and Content provided are not substitutes for medical or professional care, and you should not use the information in place of a visit, call, consultation or the advice of your physician or other healthcare provider. You are liable or responsible for any advice, course of treatment, diagnosis or any other information, services or product obtained through this site.")
        ),
        
        # Links
        p(
          a("Homepage", href = "../", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Website Error Messages", href = "javascript:sendEmail()", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (iOS Safari)", href = "https://support.apple.com/guide/iphone/bookmark-favorite-webpages-iph42ab2f3a7/ios#iph4f9a47bbc", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (Android)", href = "https://www.cnet.com/tech/mobile/adding-one-touch-bookmarks-to-your-androids-home-screen/", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Source Code", href = "https://github.com/ClevelandClinicQHS/riskcalc-website/tree/main/IrisMel", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif;font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          style = "text-align: center;"
        ),
        
        # Logo (to render on server)
        img(src = "../logo-ccf.png", style = "max-width:30%; max-height:100%;")
      )
    )
  )
