# load 1-year RCR model object - 10/15/2024
library(shiny);library(shinythemes);library(plyr);library(dplyr);library(ggplot2);library(reshape2);library(rms);library(betareg);library(Hmisc)

#Loading all of the models stored in RData file
load(file = 'RCR_MODELS.RData')

#Functions that return predictions
##PSS Total
pss_total_preds <- function(age,
                       gender,
                       race,
                       bmi,
                       cci,
                       smoking,
                       education,
                       adi,
                       insurance,
                       mcs0,
                       psydx,
                       opioid,
                       chronicpain,
                       priorsurgery,
                       teartype,
                       tearsize,
                       repairtechnique,
                       subscapstatus,
                       biceptreatment,
                       glenoidhumeralstatus,
                       acromioplasty,
                       acjoint,
                       pss0
                       ) {
  
    #Creating data frame
    new_dat <- data.frame('Age_c' = age,
                          'Sex' = gender,
                          'Race' = race,
                          'BMI_c' = bmi,
                          'CCI_c' = cci,
                          'SmokingStatus1' = smoking,
                          'Education_c' = education,
                          'ADI_c' = adi,
                          'Insurance' = insurance,
                          'MCS0_c' = mcs0,
                          'PsyDiagnosis' = psydx,
                          'Opioid1' = opioid,
                          'ChronicPain' = chronicpain,
                          'PriorSurgery' = priorsurgery,
                          'TearType' = teartype,
                          'TearSize1' = tearsize,
                          'RepairTechnique' = repairtechnique,
                          'SubscapStatusRepair' = subscapstatus,
                          'BicepTreatment' = biceptreatment,
                          'GlenoidHumeralStatus' = glenoidhumeralstatus,
                          'Acromioplasty' = acromioplasty,
                          'ACJoint' = acjoint,
                          'PSSTotal0_c' = pss0)
    mean_pred <- data.frame(mean_pred = unlist(lapply(pss1_mod_beta, predict, newdata = new_dat, type = "link")))
    quantile_pred <- do.call(rbind.data.frame, lapply(pss1_mod_beta, predict, newdata = new_dat, type = "quantile", at = c(0.1, 0.9)))
    paste0(ceil(100*mean(mean_pred[,1])),
           " (",
           floor(100*mean(quantile_pred[,1])),
           ", ",
           ceil(100*mean(quantile_pred[,2])),
           ")")
}

pss_pain_preds <- function(age,
                           gender,
                           race,
                           bmi,
                           cci,
                           smoking,
                           education,
                           adi,
                           insurance,
                           mcs0,
                           psydx,
                           opioid,
                           chronicpain,
                           priorsurgery,
                           teartype,
                           tearsize,
                           repairtechnique,
                           subscapstatus,
                           biceptreatment,
                           glenoidhumeralstatus,
                           acromioplasty,
                           acjoint,
                           pss0
) {
  
  #Creating data frame
  new_dat <- data.frame('Age_c' = age,
                        'Sex' = gender,
                        'Race' = race,
                        'BMI_c' = bmi,
                        'CCI_c' = cci,
                        'SmokingStatus1' = smoking,
                        'Education_c' = education,
                        'ADI_c' = adi,
                        'Insurance' = insurance,
                        'MCS0_c' = mcs0,
                        'PsyDiagnosis' = psydx,
                        'Opioid1' = opioid,
                        'ChronicPain' = chronicpain,
                        'PriorSurgery' = priorsurgery,
                        'TearType' = teartype,
                        'TearSize1' = tearsize,
                        'RepairTechnique' = repairtechnique,
                        'SubscapStatusRepair' = subscapstatus,
                        'BicepTreatment' = biceptreatment,
                        'GlenoidHumeralStatus' = glenoidhumeralstatus,
                        'Acromioplasty' = acromioplasty,
                        'ACJoint' = acjoint,
                        'PSSTotal0_c' = pss0)
  mean_pred <- data.frame(mean_pred = unlist(lapply(pain1_mod_beta, predict, newdata = new_dat, type = "link")))
  quantile_pred <- do.call(rbind.data.frame, lapply(pain1_mod_beta, predict, newdata = new_dat, type = "quantile", at = c(0.1, 0.9)))
  paste0(ceil(30*mean(mean_pred[,1])),
         " (",
         floor(30*mean(quantile_pred[,1])),
         ", ",
         ceil(30*mean(quantile_pred[,2])),
         ")")
}

pss_func_preds <- function(age,
                           gender,
                           race,
                           bmi,
                           cci,
                           smoking,
                           education,
                           adi,
                           insurance,
                           mcs0,
                           psydx,
                           opioid,
                           chronicpain,
                           priorsurgery,
                           teartype,
                           tearsize,
                           repairtechnique,
                           subscapstatus,
                           biceptreatment,
                           glenoidhumeralstatus,
                           acromioplasty,
                           acjoint,
                           pss0
) {
  
  #Creating data frame
  new_dat <- data.frame('Age_c' = age,
                        'Sex' = gender,
                        'Race' = race,
                        'BMI_c' = bmi,
                        'CCI_c' = cci,
                        'SmokingStatus1' = smoking,
                        'Education_c' = education,
                        'ADI_c' = adi,
                        'Insurance' = insurance,
                        'MCS0_c' = mcs0,
                        'PsyDiagnosis' = psydx,
                        'Opioid1' = opioid,
                        'ChronicPain' = chronicpain,
                        'PriorSurgery' = priorsurgery,
                        'TearType' = teartype,
                        'TearSize1' = tearsize,
                        'RepairTechnique' = repairtechnique,
                        'SubscapStatusRepair' = subscapstatus,
                        'BicepTreatment' = biceptreatment,
                        'GlenoidHumeralStatus' = glenoidhumeralstatus,
                        'Acromioplasty' = acromioplasty,
                        'ACJoint' = acjoint,
                        'PSSTotal0_c' = pss0)
  mean_pred <- data.frame(mean_pred = unlist(lapply(func1_mod_beta, predict, newdata = new_dat, type = "link")))
  quantile_pred <- do.call(rbind.data.frame, lapply(func1_mod_beta, predict, newdata = new_dat, type = "quantile", at = c(0.1, 0.9)))
  paste0(ceil(60*mean(mean_pred[,1])),
         " (",
         floor(60*mean(quantile_pred[,1])),
         ", ",
         ceil(60*mean(quantile_pred[,2])),
         ")")
}

pss_sat_preds <- function(age,
                          gender,
                          race,
                          bmi,
                          cci,
                          smoking,
                          education,
                          adi,
                          insurance,
                          mcs0,
                          psydx,
                          opioid,
                          chronicpain,
                          priorsurgery,
                          teartype,
                          tearsize,
                          repairtechnique,
                          subscapstatus,
                          biceptreatment,
                          glenoidhumeralstatus,
                          acromioplasty,
                          acjoint,
                          pss0
) {
  
  #Creating data frame
  new_dat <- data.frame('Age' = age,
                        'Sex' = gender,
                        'Race' = race,
                        'BMI' = bmi,
                        'CCI' = cci,
                        'SmokingStatus1' = smoking,
                        'Education' = education,
                        'ADI' = adi,
                        'Insurance' = insurance,
                        'MCS0' = mcs0,
                        'PsyDiagnosis' = psydx,
                        'Opioid1' = opioid,
                        'ChronicPain' = chronicpain,
                        'PriorSurgery' = priorsurgery,
                        'TearType' = teartype,
                        'TearSize1' = tearsize,
                        'RepairTechnique' = repairtechnique,
                        'SubscapStatusRepair' = subscapstatus,
                        'BicepTreatment' = biceptreatment,
                        'GlenoidHumeralStatus' = glenoidhumeralstatus,
                        'Acromioplasty' = acromioplasty,
                        'ACJoint' = acjoint,
                        'PSSTotal0' = pss0)
  q10_pred <- Predict(f, 
                      Age=new_dat$Age,
                      Sex = new_dat$Sex,
                      Race = new_dat$Race,
                      BMI = new_dat$BMI,
                      CCI = new_dat$CCI,
                      SmokingStatus1 = new_dat$SmokingStatus1,
                      Education = new_dat$Education,
                      ADI = new_dat$ADI,
                      Insurance = new_dat$Insurance,
                      MCS0 = new_dat$MCS0,
                      PsyDiagnosis = new_dat$PsyDiagnosis,
                      Opioid1 = new_dat$Opioid1,
                      ChronicPain = new_dat$ChronicPain,
                      PriorSurgery = new_dat$PriorSurgery,
                      TearType = new_dat$TearType,
                      TearSize1 = new_dat$TearSize1,
                      RepairTechnique = new_dat$RepairTechnique,
                      SubscapStatusRepair = new_dat$SubscapStatusRepair,
                      BicepTreatment = new_dat$BicepTreatment,
                      GlenoidHumeralStatus = new_dat$GlenoidHumeralStatus,
                      Acromioplasty = new_dat$Acromioplasty,
                      ACJoint = new_dat$ACJoint,
                      PSSTotal0 = new_dat$PSSTotal0,
                      fun=q10,
                      conf.int = F)
  
  q90_pred <- Predict(f, 
                      Age=new_dat$Age,
                      Sex = new_dat$Sex,
                      Race = new_dat$Race,
                      BMI = new_dat$BMI,
                      CCI = new_dat$CCI,
                      SmokingStatus1 = new_dat$SmokingStatus1,
                      Education = new_dat$Education,
                      ADI = new_dat$ADI,
                      Insurance = new_dat$Insurance,
                      MCS0 = new_dat$MCS0,
                      PsyDiagnosis = new_dat$PsyDiagnosis,
                      Opioid1 = new_dat$Opioid1,
                      ChronicPain = new_dat$ChronicPain,
                      PriorSurgery = new_dat$PriorSurgery,
                      TearType = new_dat$TearType,
                      TearSize1 = new_dat$TearSize1,
                      RepairTechnique = new_dat$RepairTechnique,
                      SubscapStatusRepair = new_dat$SubscapStatusRepair,
                      BicepTreatment = new_dat$BicepTreatment,
                      GlenoidHumeralStatus = new_dat$GlenoidHumeralStatus,
                      Acromioplasty = new_dat$Acromioplasty,
                      ACJoint = new_dat$ACJoint,
                      PSSTotal0 = new_dat$PSSTotal0,
                      fun=q90,
                      conf.int = F)
  paste0(ceil(predict(sat, newdata = new_dat, type = "mean")),
         " (", 
         floor(q10_pred$yhat),
         ", ",
         ceil(q90_pred$yhat),
         ")")
}

#Functions used to generate buttons on questionaires
pssQuestion <- function(inputId, label) {
  radioButtons(inputId = inputId,
               label = span(label,
                            style = 'font-size:16px'),
               choices = c('No difficulty' = 3,
                           'Some difficulty' = 2,
                           'Much difficulty' = 1,
                           "Can't do at all" = 0,
                           "Did not do before injury" = NA),
               inline = TRUE)
}
