#---% Generated by riskcalc: feel free to edit or 'Run App' %---
server <-

  # Define the server
  function(input, output, session) {
    
    # Switch panel
    panelSwtich <- reactive({gsub(" ", "_", paste(input$sex, input$absSmok, sep=" "))})
    observeEvent(panelSwtich(), {
      updateTabsetPanel(inputId = "params", selected = panelSwtich())
    })
    
    # Valid age
    ageVal <- reactive({
      age <- floor(as.numeric(input$AgeYr))
      test <- all(age >= 30, age <= 85, !is.na(age))
      shinyFeedback::feedbackWarning("AgeYr", !test, "Please enter an age between 30 and 85")
      ageList <- c("risk30_35" , "risk35_40" , "risk40_45" , "risk45_50" , "risk50_55" , 
                   "risk55_60" , "risk60_65" , "risk65_70" , "risk70_75" , "risk75_80" , 
                   "risk80_85")
      numList <- c(list(30:34), list(35:39), list(40:44), list(45:49), list(50:54),
                   list(55:59), list(60:64), list(65:69), list(70:74), list(75:79),
                   list(80:85))
      req(test)
      ageList[unlist(lapply(numList, function(x) age %in% x))]
    })
    
    # output$testTXT <- renderText(ageVal())
    inputTrackCalculate <- reactiveVal("init")
    inputTrackCurrent <- reactive({paste0(input$AgeYr, input$sex, input$absSmok, 
                                          input$maleSmk, input$maleSmkAlc, input$maleSmkPA,
                                          input$maleSmkCanHist, input$maleSmkDiet,
                                          input$femaleSmk, input$femaleSmkAlc, input$femaleSmkBMI,
                                          input$femaleSmkCanHist, input$femaleSmkDiabete, input$femaleSmkHyper, 
                                          input$femaleSmkHyste, input$femaleSmkTL, 
                                          input$femaleSmkPar, input$maleAbsBMI, input$maleAbsCanHist, input$maleAbsDiabete, 
                                          input$maleAbsHyper, input$femaleAbsBMI, input$femaleAbsCanHist,
                                          input$femaleAbsHyper, input$femalekAbsHyste, input$femaleAbsTL,
                                          input$femaleAbsPar)})
    # observe({
    #   print(paste("Cal--", inputTrackCalculate()))
    #   print(paste("IN--", inputTrackCurrent()))
    #   print(inputTrackCalculate() == inputTrackCurrent())
    # })
    observe({
      if (inputTrackCalculate() != inputTrackCurrent()) {
        output$testTXT <- renderUI({
          div( HTML(sprintf("<text style='color:%s'> please click \"Run Calculate\" to get the risk </text>", "rgb(255, 165, 0)")))
        })
      } else {
        output$testTXT <- renderUI({
          div( HTML(sprintf("<text style='color:%s'>  </text>", "rgb(255, 165, 0)")))
        })
      }
    })
    
    # observeEvent(inputChangeTrack(), {
    #               shinyFeedback::feedbackWarning("AgeYr", T, "Please press Run Calculator to refresh results")})

    # Make a reactive input data frame
    input_data <-
      eventReactive(
        input$run_calculator, {
          # shinyFeedback::hideFeedback("AgeYr")
          test = ageVal() # this is for feedbackWarning purpose
          inputTrackCalculate(paste0(input$AgeYr, input$sex, input$absSmok, 
                                     input$maleSmk, input$maleSmkAlc, input$maleSmkPA,
                                     input$maleSmkCanHist, input$maleSmkDiet,
                                     input$femaleSmk, input$femaleSmkAlc, input$femaleSmkBMI,
                                     input$femaleSmkCanHist, input$femaleSmkDiabete, input$femaleSmkHyper, 
                                     input$femaleSmkHyste, input$femaleSmkTL, 
                                     input$femaleSmkPar, input$maleAbsBMI, input$maleAbsCanHist, input$maleAbsDiabete, 
                                     input$maleAbsHyper, input$femaleAbsBMI, input$femaleAbsCanHist,
                                     input$femaleAbsHyper, input$femalekAbsHyste, input$femaleAbsTL,
                                     input$femaleAbsPar)) # this is for tracking input change and reminding re-calculate purpose
          finalData = switch(panelSwtich(),
                             Male_Yes = {data.table(
                               current_alcohol_use = as.numeric(factor(input$maleSmkAlc, levels = c("None", 
                                                                                                    "< 1 / day",
                                                                                                    "1 - 2 / day",
                                                                                                    "> 2 / day"))) - 1,
                               family_history_of_cancer = as.numeric(factor(input$maleSmkCanHist, levels = c('No', 'Yes'))) - 1,
                               smoking_history = as.numeric(factor(input$maleSmk, levels = c("Never smoker", 
                                                                                             "Former smoker >= 10 years since quiting",
                                                                                             "Former smoker < 10 years since quiting",
                                                                                             "Current"))),
                               diet = as.numeric(factor(input$maleSmkDiet, levels = c('No', 'Yes'))) - 1,
                               physical_activity = as.numeric(factor(input$maleSmkPA, levels = c("None", 
                                                                                                 "< 7.5",
                                                                                                 ">= 7.5")))
                               
                             )},
                             
                             Female_Yes = {data.table(
                               current_alcohol_use = as.numeric(factor(input$femaleSmkAlc, levels = c("None", 
                                                                                                    "< 1 / day",
                                                                                                    "1 - 2 / day",
                                                                                                    "> 2 / day"))) - 1,
                               BMI = as.numeric(factor(input$femaleSmkBMI, levels = c(">= 18.5 and < 25", 
                                                                                      ">= 25 and < 30",
                                                                                      "> = 30"))),
                               diabetes = as.numeric(factor(input$femaleSmkDiabete, levels = c('No', 'Yes'))) - 1,
                               family_history_of_cancer = as.numeric(factor(input$femaleSmkCanHist, levels = c('No', 'Yes'))) - 1,
                               hypertension = as.numeric(factor(input$femaleSmkHyper, levels = c('No', 'Yes'))) - 1,
                               hysterectomy = as.numeric(factor(input$femaleSmkHyste, levels = c('No', 'Yes'))) - 1,
                               smoking_history = as.numeric(factor(input$femaleSmk, levels = c("Never smoker", 
                                                                                     "Former smoker >= 10 years since quiting",
                                                                                     "Former smoker < 10 years since quiting",
                                                                                     "Current"))),
                               parity = as.numeric(factor(input$femaleSmkPar, levels = c('Nulliparous', 'Parous'))),
                               tubal_ligation = as.numeric(factor(input$femaleSmkTL, levels = c('No', 'Yes'))) - 1
                             )},
                             
                             Male_No = {data.table(
                               BMI = as.numeric(factor(input$maleAbsBMI, levels = c(">= 18.5 and < 25", 
                                                                                      ">= 25 and < 30",
                                                                                      "> = 30"))),
                               diabetes = as.numeric(factor(input$maleAbsDiabete, levels = c('No', 'Yes'))) - 1,
                               family_history_of_cancer = as.numeric(factor(input$maleAbsCanHist, levels = c('No', 'Yes'))) - 1,
                               hypertension = as.numeric(factor(input$maleAbsHyper, levels = c('No', 'Yes'))) - 1
                             )},
                             
                             Female_No = {data.table(
                               BMI = as.numeric(factor(input$femaleAbsBMI, levels = c(">= 18.5 and < 25", 
                                                                                    ">= 25 and < 30",
                                                                                    "> = 30"))),
                               family_history_of_cancer = as.numeric(factor(input$femaleAbsCanHist, levels = c('No', 'Yes'))) - 1,
                               hypertension = as.numeric(factor(input$femaleAbsHyper, levels = c('No', 'Yes'))) - 1,
                               hysterectomy = as.numeric(factor(input$femalekAbsHyste, levels = c('No', 'Yes'))) - 1,
                               parity = as.numeric(factor(input$femaleAbsPar, levels = c('Nulliparous', 'Parous'))),
                               tubal_ligation = as.numeric(factor(input$femaleAbsTL, levels = c('No', 'Yes'))) - 1
                             )}
                            )
          finalData})
    
    # Load lookup table
    S7Women <<- readRDS("www/S7Women.rds")
    S6men <<- readRDS("www/S6Men.rds")
    S3SmokeMen <<- readRDS("www/S3SmokeMen.rds")
    S4SmokeWomen <<- readRDS("www/S4SmokeWomen.rds")
    
    # observe({print(pryr::where("S7Women"))})
    
    # Map risk
    mapRiskVal <- eventReactive(input_data(),{
                                mapRisk(panelSwtich(), input_data(), ageVal())}) # function warp in helper.R
    
    # Show result
    output$result <-
      renderDataTable(
        {

          # Make the data frame containing results
          data.frame(Result = "Predicted Absolute 5-Year Risk of Developing Any Invasive Cancer", Risk = paste0(mapRiskVal(),"%")) 

        },
        options =
          list(
            pageLength = 10,
            lengthMenu = 0,
            searching = 0,
            info = 0,
            paging = 0,
            initComplete =
              DT::JS(
                "function(settings, json) {
                    $(this.api().table().header()).css({'background-color': '#606060', 'color': '#fff'});
                  }"
              )
          ),
        rownames = FALSE
      )
    
    

  }
