# show tabs based on sex and smoking history
parameter_tabs <- tabsetPanel(
  id = "params",
  type = "hidden",
  tabPanel("Male_Yes",
           selectInput("maleSmk", "Smoking History", choices = c("Never smoked", 
                                                                 "Previously smoked >= 10 years since quiting",
                                                                 "Previously smoked < 10 years since quiting",
                                                                 "Current")),
           selectInput("maleSmkAlc", "Current Alcohol Use (number of drinks per day)", choices = c("None", 
                                                                        "< 1 / day",
                                                                        "1 - 2 / day",
                                                                        "> 2 / day")),
           selectInput("maleSmkPA", "Physical Activity (number of hours per week)", choices = c("None", 
                                                                     "< 7.5",
                                                                     ">= 7.5")),
           radioButtons('maleSmkCanHist', "First-degree Family History of Cancer", choices = c('No', 'Yes')),
           radioButtons('maleSmkDiet', "Limited Red Meat Consumption", choices = c('No', 'Yes'))
  ),
  
  tabPanel("Female_Yes",
           selectInput("femaleSmk", "Smoking History", choices = c("Never smoked", 
                                                                   "Previously smoked >= 10 years since quiting",
                                                                   "Previously smoked < 10 years since quiting",
                                                                   "Current")),
           selectInput("femaleSmkAlc", "Current Alcohol Use (number of drinks per day)", choices = c("None", 
                                                                          "< 1 / day",
                                                                          "1 - 2 / day",
                                                                          "> 2 / day")),
           selectInput("femaleSmkBMI", "Body Mass Index", choices = c(">= 18.5 and < 25", 
                                                                      ">= 25 and < 30",
                                                                      "> = 30")),
           radioButtons('femaleSmkCanHist', "First-degree Family History of Cancer", choices = c('No', 'Yes')),
           radioButtons('femaleSmkDiabete', "Diabetes", choices = c('No', 'Yes')),
           radioButtons('femaleSmkHyper', "Hypertension", choices = c('No', 'Yes')),
           radioButtons('femaleSmkHyste', "Hysterectomy", choices = c('No', 'Yes')),
           radioButtons('femaleSmkTL', "Tubal Ligation", choices = c('No', 'Yes')),
           radioButtons('femaleSmkPar', "Parity", choices = c('Nulliparous', 'Parous'))
           
  ),
  
  tabPanel("Male_No",
           selectInput("maleAbsBMI", "Body Mass Index", choices = c(">= 18.5 and < 25", 
                                                                      ">= 25 and < 30",
                                                                      "> = 30")),
           radioButtons('maleAbsCanHist', "First-degree Family History of Cancer", choices = c('No', 'Yes')),
           radioButtons('maleAbsDiabete', "Diabetes", choices = c('No', 'Yes')),
           radioButtons('maleAbsHyper', "Hypertension", choices = c('No', 'Yes'))
  ),
  
  tabPanel("Female_No",
           selectInput("femaleAbsBMI", "Body Mass Index", choices = c(">= 18.5 and < 25", 
                                                                 ">= 25 and < 30",
                                                                 "> = 30")),
           radioButtons('femaleAbsCanHist', "First-degree Family History of Cancer", choices = c('No', 'Yes')),
           radioButtons('femaleAbsHyper', "Hypertension", choices = c('No', 'Yes')),
           radioButtons('femalekAbsHyste', "Hysterectomy", choices = c('No', 'Yes')),
           radioButtons('femaleAbsTL', "Tubal Ligation", choices = c('No', 'Yes')),
           radioButtons('femaleAbsPar', "Parity", choices = c('Nulliparous', 'Parous'))
  )
)

#---% Generated by riskcalc: feel free to edit or 'Run App' %---
ui <-

  # Make the page
  fluidPage(
  
    # Set the (default) theme
    theme = shinytheme("flatly"),
    shinyFeedback::useShinyFeedback(),

    # Function for email prompting
    tags$script(
      HTML(
        'function sendEmail() {
        var txt;
        if (confirm("This is a mailbox for reporting website errors to programmers for the risk calculator website.  If you have questions or concerns about a specific calculator, please use the calculator Author Contact Information found on the publication for that calculator.  Each calculator is documented by a specific publication with a corresponding author.")) {
          window.open("mailto:rcalcsupport@ccf.org");
        }
      }'
      )
    ),

    # Tag for tracking app usage (on server) via Google Analytics
    tags$head(ga_tag),

    # Make the title panel
    titlePanel("Predicting Absolute 5-Year Risk of Developing Any Invasive Cancer"),

    # Make the default layout
    sidebarLayout(

      # Create the side bar with input objects
      sidebarPanel(id = "sidebar",
                   textInput('AgeYr', 'Age (Years)', placeholder = '30 - 85'),
                   radioButtons('sex', 'Sex', choices = c('Female', 'Male')),
                   radioButtons('absSmok', "Do You Know Patient's Smoking History?", choices = c('No', 'Yes')),
                   parameter_tabs
                   ),

      # Create the main display panel
      mainPanel(
        
        # textOutput("testTXT"),
        
        # Add button for calculation
        fluidRow(
          column(2,
                 "",
                 actionButton(inputId = "run_calculator", "Run Calculator")
                 ),
          column(6,
                 " ",
                 htmlOutput("testTXT"),
          )
        ),
        # actionButton(inputId = "run_calculator", "Run Calculator"), 
        # br(),
        hr(),
        
        
        
        # Make the table output
        dataTableOutput(outputId = "result"),
        br(),

        ## Information panels/links

        # Citation
        wellPanel(
          h3("Click Below for Author Information"),
          p("[1] Patel, A. V., Deubler, E., Teras, L. R., Colditz, G. A., Lichtman, C. J., Cance, W. G., & Clarke, C. A. ",
            a(' Key risk factors for the relative and absolute 5-year risk of cancer to enhance cancer screening and prevention', 
              href='https://acsjournals.onlinelibrary.wiley.com/doi/10.1002/cncr.34396'),
            ". Cancer, 128(19), 3502-3515.")
        ),

        # Disclaimer
        wellPanel(
          h3("Disclaimer"),
          p("No Medical Advice. ALTHOUGH SOME CONTENT MAY BE PROVIDED BY INDIVIDUALS IN THE MEDICAL PROFESSION, YOU ACKNOWLEDGE THAT PROVISION OF SUCH CONTENT DOES NOT CREATE A MEDICAL PROFESSIONAL-PATIENT RELATIONSHIP AND DOES NOT CONSTITUTE AN OPINION, MEDICAL ADVICE, PROFESSIONAL DIAGNOSIS, SERVICE OR TREATMENT OF ANY CONDITION. Access to general information is provided for educational purposes only, through this site and links to other sites. Content is not recommended or endorsed by any doctor or healthcare provider. The information and Content provided are not substitutes for medical or professional care, and you should not use the information in place of a visit, call, consultation or the advice of your physician or other healthcare provider. You are liable or responsible for any advice, course of treatment, diagnosis or any other information, services or product obtained through this site.")
        ),

        # Links
        p(
          a("Homepage", href = "../", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Website Error Messages", href = "javascript:sendEmail()", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (iOS Safari)", href = "https://support.apple.com/guide/iphone/bookmark-favorite-webpages-iph42ab2f3a7/ios#iph4f9a47bbc", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (Android)", href = "https://www.cnet.com/tech/mobile/adding-one-touch-bookmarks-to-your-androids-home-screen/", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Source Code", href = "https://github.com/ClevelandClinicQHS/riskcalc-website/tree/main/InvasiveCancer", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif;font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          style = "text-align: center;"
        ),

        # Logo (to render on server)
        img(src = "../logo-ccf.png", style = "max-width:30%; max-height:100%;")
      )
    )
  )



