#---% Generated by riskcalc: feel free to edit or 'Run App' %---

# Load packages
library(shiny)
library(shinythemes)
library(htmltools)
library(DT)

# Set Google Analytics
ga_tag <- "../google-analytics.html"
if(file.exists(ga_tag)) {
  ga_tag <- includeHTML(ga_tag)
} else {
  ga_tag <- NULL
}

# Function to predict readmission risk
predict_readmission_risk <-
  function(input_data) {
    
    log_odds <- 
      with(
        data = input_data,
        0.0122 +
          0.0658 * number_of_admissions + 
          0.0451 * number_of_ed_visits + 
          0.3365 + ed_visit +
          0 * admission_class_inpatient +
          -0.2624 * admission_class_observation +
          0 * discharge_disposition_acute + 
          0.0878 * discharge_disposition_home + 
          0.0131 * discharge_disposition_homecare + 
          -2.6391 * discharge_disposition_hospice + 
          -0.1612 * discharge_disposition_snf + 
          -0.6663 * discharge_disposition_other + 
          0.2038 * ckd +
          0.2645 * chronic_lung_disease + 
          0.1580 * anemia +
          0.0338 * medication_count + 
          0.1617 * anticoagulation_meds +
          -0.0344 * hemoglobin +
          0.1102 * calcium +
          0.0053 * bun +
          -0.2772 * albumin +
          -0.0205 * sodium +
          0.2751 * drug_abuse +
          0.4617 * insurance_medicaid +
          0.3600 * insurance_medicare +
          0.2964 * insurance_private +
          0.0882 * insurance_self +
          0 * insurance_other +
          0.4890 * language_barriers
      )
    
    1 / (1 + exp(-log_odds))
    
  }
