#---% Generated by riskcalc: feel free to edit or 'Run App' %---
server <-
  
  # Define the server
  function(input, output, session) {
    
    # Make a reactive input data frame
    input_data <-
      eventReactive(
        input$run_calculator, {
          
          # Create input data frame
          data.frame(
            number_of_admissions = input$number_of_admissions, 
            number_of_ed_visits = input$number_of_ed_visits,
            ed_visit = as.numeric(input$number_of_ed_visits > 0),
            admission_class_inpatient = as.numeric(input$admission_class == "Inpatient"),
            admission_class_observation = as.numeric(input$admission_class == "Observation"),
            discharge_disposition_acute = as.numeric(input$discharge_disposition == "Acute Care Facility"),
            discharge_disposition_home = as.numeric(input$discharge_disposition == "Home"),
            discharge_disposition_homecare = as.numeric(input$discharge_disposition == "Home w/ Care"),
            discharge_disposition_hospice = as.numeric(input$discharge_disposition == "Hospice"),
            discharge_disposition_snf = as.numeric(input$discharge_disposition == "SNF"),
            discharge_disposition_other = as.numeric(input$discharge_disposition == "Other"),
            ckd = as.numeric("CKD" %in% input$medical_history),
            chronic_lung_disease = as.numeric("Chronic Lung Disease" %in% input$medical_history),
            anemia = as.numeric("Anemia" %in% input$medical_history),
            medication_count = input$medication_count, 
            anticoagulation_meds = as.numeric(input$anticoagulation_meds),
            hemoglobin = input$hemoglobin,
            calcium = input$calcium,
            bun = input$bun,
            albumin = input$albumin,
            sodium = input$sodium,
            drug_abuse = as.numeric(input$drug_abuse),
            insurance_medicaid = as.numeric(input$insurance == "Medicaid"),
            insurance_medicare = as.numeric(input$insurance == "Medicare"),
            insurance_private = as.numeric(input$insurance == "Private"),
            insurance_self = as.numeric(input$insurance == "Self-Pay"),
            insurance_other = as.numeric(input$insurance == "Other"),
            language_barriers = as.numeric(input$language_barriers)
          )
          
        })
    
    # Show result
    output$result <-
      renderDataTable(
        {
          
          # Make the data frame containing results
          data.frame(Result = "30-Day Readmission Risk (%)", Value = paste0(round(100 * predict_readmission_risk(input_data()), 2), "%"))
          
        },
        options =
          list(
            pageLength = 10,
            lengthMenu = 0,
            searching = 0,
            info = 0,
            paging = 0,
            initComplete =
              DT::JS(
                "function(settings, json) {
                    $(this.api().table().header()).css({'background-color': '#606060', 'color': '#fff'});
                  }"
              )
          ),
        rownames = FALSE
      )
    
  }
