#---% Generated by riskcalc: feel free to edit or 'Run App' %---
ui <-

  # Make the page
  fluidPage(

    # Set the (default) theme
    theme = shinytheme("flatly"),

    # Function for email prompting
    tags$script(
      HTML(
        'function sendEmail() {
        var txt;
        if (confirm("This is a mailbox for reporting website errors to programmers for the risk calculator website.  If you have questions or concerns about a specific calculator, please use the calculator Author Contact Information found on the publication for that calculator.  Each calculator is documented by a specific publication with a corresponding author.")) {
          window.open("mailto:rcalcsupport@ccf.org");
        }
      }'
      )
    ),

    # Tag for tracking app usage (on server) via Google Analytics
    tags$head(ga_tag),

    # Make the title panel
    titlePanel("Readmission Risk Score"),

    # Make the default layout
    sidebarLayout(

      # Create the side bar with input objects
      sidebarPanel(
        
        ## Healthcare utilization
        h3("Healthcare Utilization"),
        
        # Number of hospital admissions in the past year
        numericInput(
          inputId = "number_of_admissions",
          label = "Number of Admissions in Past Year",
          value = 0,
          min = 0
        ),
        
        # Number of ED visits in past 6 months (input determines binary variable for ED visit in past 6 months)
        numericInput(
          inputId = "number_of_ed_visits",
          label = "Number of ED Visits in Past Year",
          value = 0,
          min = 0
        ),
        
        # Admission class
        selectInput(
          inputId = "admission_class",
          label = "Admission Class",
          choices = c("Inpatient", "Observation")
        ),
        
        # Discharge disposition
        selectInput(
          inputId = "discharge_disposition",
          label = "Discharge Disposition",
          choices = 
            c(
              "Acute Care Facility",
              "Home",
              "Home w/ Care",
              "Hospice",
              "SNF",
              "Other"
            )
        ),
        
        ## Medical History
        h3("Medical History"),
        
        # Comorbidity list
        checkboxGroupInput(
          inputId = "medical_history",
          label = "Comorbidities",
          choices = c("CKD", "Chronic Lung Disease", "Anemia")
        ),
        
        ## Medications
        h3("Medications"),
        
        # Number of active medications
        numericInput(
          inputId = "medication_count",
          label = "Number of Active Medications",
          value = 0,
          min = 0
        ),
        
        # On acticoagulation meds?
        checkboxInput(
          inputId = "anticoagulation_meds",
          label = "On Anticoagulation Medication?"
        ),
        
        ## Labs
        h3("Laboratory Analysis"),
        
        # Admission labs
        h5("At Admission"),
        
        # Hemoglobin
        numericInput(
          inputId = "hemoglobin",
          label = "Hemoglobin",
          value = 0,
          min = 0
        ),
        
        # Calcium
        numericInput(
          inputId = "calcium",
          label = "Calcium",
          value = 0,
          min = 0
        ),
        
        # Discharge labs
        h5("At Discharge"),
        
        # BUN
        numericInput(
          inputId = "bun",
          label = "BUN",
          value = 0,
          min = 0
        ),
        
        # Albumin
        numericInput(
          inputId = "albumin",
          label = "Albumin",
          value = 0,
          min = 0
        ),
        
        # Sodium
        numericInput(
          inputId = "sodium",
          label = "Sodium",
          value = 0,
          min = 0
        ),
        
        ## Socieconomic/behavior
        h3("Socioeconomic and Behavioral"),
        
        # Drug abuse
        checkboxInput(
          inputId = "drug_abuse",
          label = "Drug Abuse?"
        ),
        
        # Insurance
        selectInput(
          inputId = "insurance",
          label = "Insurance",
          choices = 
            c(
              "Medicaid",
              "Medicare",
              "Private",
              "Self-Pay",
              "Other"
            )
        ),
        
        # Barriers
        checkboxInput(
          inputId = "language_barriers",
          label = "Language Barrier, Poor Health Literacy, or Impaired Cognition"
        )
        
      ),

      # Create the main display panel
      mainPanel(

        # Add button for calculation
        actionButton(inputId = "run_calculator", "Run Calculator"),
        br(),
        hr(),

        # Make the table output
        dataTableOutput(outputId = "result"),
        br(),

        ## Information panels/links

        # Citation
        wellPanel(
          h3("Click Below for Calculator and Author Contact Information"),
          htmltools::HTML("<p>[1] Misra-Hebert, A.D., Felix, C., Milinovich, A. et al. 
                          <a href = 'https://link.springer.com/article/10.1007/s11606-021-07277-4#citeas'> Implementation Experience with a 30-Day Hospital Readmission Risk Score in a Large, Integrated Health System: A Retrospective Study.</a>
                          J GEN INTERN MED 37, 3054–3061 (2022). https://doi.org/10.1007/s11606-021-07277-4</p>"),
          
        ),

        # Disclaimer
        wellPanel(
          h3("Disclaimer"),
          p("No Medical Advice. ALTHOUGH SOME CONTENT MAY BE PROVIDED BY INDIVIDUALS IN THE MEDICAL PROFESSION, YOU ACKNOWLEDGE THAT PROVISION OF SUCH CONTENT DOES NOT CREATE A MEDICAL PROFESSIONAL-PATIENT RELATIONSHIP AND DOES NOT CONSTITUTE AN OPINION, MEDICAL ADVICE, PROFESSIONAL DIAGNOSIS, SERVICE OR TREATMENT OF ANY CONDITION. Access to general information is provided for educational purposes only, through this site and links to other sites. Content is not recommended or endorsed by any doctor or healthcare provider. The information and Content provided are not substitutes for medical or professional care, and you should not use the information in place of a visit, call, consultation or the advice of your physician or other healthcare provider. You are liable or responsible for any advice, course of treatment, diagnosis or any other information, services or product obtained through this site.")
        ),

        # Links
        p(
          a("Homepage", href = "../", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Website Error Messages", href = "javascript:sendEmail()", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (iOS Safari)", href = "https://support.apple.com/guide/iphone/bookmark-favorite-webpages-iph42ab2f3a7/ios#iph4f9a47bbc", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Add to phone (Android)", href = "https://www.cnet.com/tech/mobile/adding-one-touch-bookmarks-to-your-androids-home-screen/", target = "_blank", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif; font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          " | ",
          a("Source Code", href = "https://github.com/ClevelandClinicQHS/riskcalc-website/tree/main/ReadmissionRiskScore", style = "font-family: 'Lato','Helvetica Neue',Helvetica,Arial,sans-serif;font-size: 15px;color: #2c3e50;font-weight: bold;text-align: center;text-decoration: underline;"),
          style = "text-align: center;"
        ),

        # Logo (to render on server)
        img(src = "../logo-ccf.png", style = "max-width:30%; max-height:100%;")
      )
    )
  )
